// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package meModel

//在下面填写您的想法。
func Alias(a string) string {
	return Table + " " + a
}
