# HTTP Server
[server]
	Address     = ":8088"
	ServerRoot  = "public"
	ServerAgent = "myapp"
	LogPath     = "./log/"

# Logger.
[logger]
    Path        = "./log/"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:123456@tcp(127.0.0.1:3306)/jie"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "./log/"
        Level  = "all"
        Stdout = true

# Redis数据库配置
[redis]
    default = "127.0.0.1:6379,0"
