// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package tagModel

// Fill with you ideas below.
func Alias(a string) string {
	return Table + " " + a
}
